"""Catalog, prices, promotions and application tables.

Phase 2 onward. Adds the geo columns to `stores` (plain lat/lng, no PostGIS --
ADR-011), pg_trgm for fuzzy Hebrew product search, and the SCD2 price history.

Original autogenerate header

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-11 01:16:14.012278
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Hebrew product search has to tolerate spelling variation; trigram
    # similarity is what makes that work (Phase 3 acceptance criterion).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_he', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('name_he', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('pack_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit_of_measure', sa.Text(), nullable=True),
    sa.Column('base_size', sa.Numeric(precision=12, scale=3), sa.Computed('pack_count * unit_size', persisted=True), nullable=True),
    sa.Column('chain_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('user_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_items',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_products.id'], ),
    sa.PrimaryKeyConstraint('basket_id', 'canonical_id')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('threshold_type', sa.Text(), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_daily',
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('store_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_products.id'], ),
    sa.PrimaryKeyConstraint('canonical_id', 'day')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.Text(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('item_type', sa.SmallInteger(), nullable=True),
    sa.Column('raw_name_he', sa.Text(), nullable=False),
    sa.Column('is_weighted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_private_label', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('match_method', sa.Text(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_products.id'], ),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'item_code')
    )
    op.create_index('idx_pv_barcode', 'product_variants', ['barcode'], unique=False)
    op.create_index('idx_pv_canonical', 'product_variants', ['canonical_id'], unique=False)
    op.create_table('price_base',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('price_group_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['price_group_id'], ['price_groups.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pb_open', 'price_base', ['price_group_id', 'variant_id'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('price_current',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('normalized_unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'variant_id')
    )
    op.create_index('idx_pc_canonical', 'price_current', ['canonical_id'], unique=False)
    op.create_table('price_exception',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pe_open', 'price_exception', ['store_id', 'variant_id'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('promotions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('promo_code', sa.Text(), nullable=True),
    sa.Column('description_he', sa.Text(), nullable=True),
    sa.Column('promo_kind', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Text(), nullable=True),
    sa.Column('reward_type', sa.Text(), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('discounted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_purchase_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('club_id', sa.Text(), nullable=True),
    sa.Column('allow_stacking', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=True),
    sa.Column('applicable_v1', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promo_active', 'promotions', ['store_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index('idx_promo_chain', 'promotions', ['chain_id'], unique=False)
    op.create_table('promotion_items',
    sa.Column('promotion_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('is_gift', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('promotion_id', 'variant_id')
    )
    op.add_column('stores', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('geocode_confidence', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "idx_cp_name_trgm",
        "canonical_products",
        ["name_he"],
        postgresql_using="gin",
        postgresql_ops={"name_he": "gin_trgm_ops"},
    )
    op.create_index("idx_stores_latlng", "stores", ["lat", "lng"])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("idx_stores_latlng", table_name="stores")
    op.drop_index("idx_cp_name_trgm", table_name="canonical_products")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'geocoded_at')
    op.drop_column('stores', 'geocode_confidence')
    op.drop_column('stores', 'lng')
    op.drop_column('stores', 'lat')
    op.drop_table('promotion_items')
    op.drop_index('idx_promo_chain', table_name='promotions')
    op.drop_index('idx_promo_active', table_name='promotions')
    op.drop_table('promotions')
    op.drop_index('idx_pe_open', table_name='price_exception', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('price_exception')
    op.drop_index('idx_pc_canonical', table_name='price_current')
    op.drop_table('price_current')
    op.drop_index('idx_pb_open', table_name='price_base', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('price_base')
    op.drop_index('idx_pv_canonical', table_name='product_variants')
    op.drop_index('idx_pv_barcode', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_table('price_daily')
    op.drop_table('price_alerts')
    op.drop_table('basket_items')
    op.drop_table('user_locations')
    op.drop_table('canonical_products')
    op.drop_table('baskets')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
